default_language_version:
  python: python3.12

default_stages: [ commit, push ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py312-plus
        types: [ python ]
        language: system

  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: poetry run autoflake
        types: [ python ]
        language: system

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
      - id: add-trailing-comma

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --settings-path pyproject.toml
        types: [ python ]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        types: [ python ]
        language: system

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8
        types: [ python ]
        language: system
